# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b6a94baed23c2733626971af9d5d6082527ec24804da9311b15cc06ee82991c826df4825a4adcdb0fdfc6e6d38cc5ad550ed1268902da29822233d904b73b61

test:
  secret_key_base: f6841aafac1fc30b539c75dc521426ad47582b8c04ba76c71e5ce22ccbc706ee6df70891bfec3dc2695052fbc86fae025e19ad0cd79a92bce0f8af36b057b563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
